'use strict';
const S = window.KuboStorage; let data = S.loadData(); let productImagesDraft=[]; let bannerImageDraft='';
function $(id){return document.getElementById(id)}
function toast(msg){ alert(msg); }
function initLogin(){ if(sessionStorage.getItem('kubo_admin_login')==='1') showApp(); $('login-btn').onclick=()=>{ data=S.loadData(); if($('login-pw').value===data.settings.adminPassword){ sessionStorage.setItem('kubo_admin_login','1'); showApp(); } else alert('パスワードが違います'); }; $('logout').onclick=()=>{sessionStorage.removeItem('kubo_admin_login'); location.reload();}; }
function showApp(){ $('login').classList.add('hidden'); $('app').classList.remove('hidden'); renderAll(); }
function initNav(){ document.querySelectorAll('.side-btn[data-page]').forEach(btn=>btn.onclick=()=>{ document.querySelectorAll('.side-btn').forEach(b=>b.classList.remove('active')); btn.classList.add('active'); document.querySelectorAll('.admin-page').forEach(p=>p.classList.remove('active')); $('page-'+btn.dataset.page).classList.add('active'); if(btn.dataset.page==='preview') refreshPreview(); }); }
function setupEditor(toolbarId, editorId){ const bar=$(toolbarId); bar.innerHTML=`<button type="button" data-cmd="bold">太字</button><button type="button" data-cmd="insertUnorderedList">箇条書き</button><button type="button" data-cmd="formatBlock" data-val="h2">見出し</button><button type="button" data-link="1">リンク</button><select data-font><option value="">フォント</option><option value="sans-serif">ゴシック</option><option value="serif">明朝</option><option value="cursive">手書き風</option></select><input type="color" data-color value="#28455a">`; bar.querySelectorAll('button[data-cmd]').forEach(b=>b.onclick=()=>{ document.execCommand(b.dataset.cmd,false,b.dataset.val||null); $(editorId).focus(); }); bar.querySelector('[data-link]').onclick=()=>{ const url=prompt('リンクURLを入力'); if(url) document.execCommand('createLink',false,url); }; bar.querySelector('[data-font]').onchange=e=>{ if(e.target.value) document.execCommand('fontName',false,e.target.value); }; bar.querySelector('[data-color]').onchange=e=>document.execCommand('foreColor',false,e.target.value); }
function renderAll(){ data=S.loadData(); renderDashboard(); fillSite(); renderProducts(); renderBanners(); renderOrders(); fillSettings(); renderImageThumbs(); }
function renderDashboard(){ $('stat-products').textContent=data.products.length; $('stat-orders').textContent=data.orders.length; $('stat-notices').textContent=data.notifications.length; $('notification-list').innerHTML=data.notifications.slice(0,20).map(n=>`<div class="notice"><strong>${S.escapeHTML(n.title)}</strong><br>${S.escapeHTML(n.message)}<br><span class="muted">${new Date(n.createdAt).toLocaleString('ja-JP')} / 通知先：${S.escapeHTML(n.to)}</span></div>`).join('')||'<p class="muted">通知はありません</p>'; }
function fillSite(){ const site=data.site; $('site-title').value=site.title; $('instagram-url').value=site.instagramUrl; $('catchcopy').value=site.catchcopy; $('subcopy').value=site.subcopy; $('store-info').value=site.storeInfo; $('business-hours').value=site.businessHours; $('shop-guide').value=site.shopGuide; $('footer-text').value=site.footerText; $('notices').value=(site.notices||[]).join('\n'); $('story-title').value=site.sections.storyTitle; $('story-body').innerHTML=site.sections.storyBody; $('product-title').value=site.sections.productTitle; $('product-body').innerHTML=site.sections.productBody; $('shop-title').value=site.sections.shopTitle; $('shop-body').innerHTML=site.sections.shopBody; }
function saveSite(){ data=S.loadData(); Object.assign(data.site,{title:$('site-title').value,instagramUrl:$('instagram-url').value,catchcopy:$('catchcopy').value,subcopy:$('subcopy').value,storeInfo:$('store-info').value,businessHours:$('business-hours').value,shopGuide:$('shop-guide').value,footerText:$('footer-text').value,notices:$('notices').value.split('\n').map(x=>x.trim()).filter(Boolean)}); data.site.sections={storyTitle:$('story-title').value,storyBody:S.safeHTML($('story-body').innerHTML),productTitle:$('product-title').value,productBody:S.safeHTML($('product-body').innerHTML),shopTitle:$('shop-title').value,shopBody:S.safeHTML($('shop-body').innerHTML)}; data=S.saveData(data); renderAll(); toast('保存しました'); }
function clearProduct(){ productImagesDraft=[]; ['product-id','product-name','product-price','product-category','product-description','product-material','product-recommend'].forEach(id=>$(id).value=''); $('product-visible').value='true'; renderProductThumbs(); }
function editProduct(id){ const p=data.products.find(x=>x.id===id); if(!p)return; $('product-id').value=p.id; $('product-name').value=p.name; $('product-price').value=p.price; $('product-category').value=p.category; $('product-description').value=p.description; $('product-material').value=p.material; $('product-recommend').value=p.recommend; $('product-visible').value=String(p.visible); productImagesDraft=[...(p.images||[])]; renderProductThumbs(); document.querySelector('[data-page="products"]').click(); }
function deleteProduct(id){ if(!confirm('商品を削除しますか？'))return; data.products=data.products.filter(p=>p.id!==id); data=S.saveData(data); renderProducts(); }
function saveProduct(){ const id=$('product-id').value||S.generateId('product'); const item={id,name:$('product-name').value||'無題の商品',price:Number($('product-price').value||0),category:$('product-category').value||'未分類',description:$('product-description').value,material:$('product-material').value,recommend:$('product-recommend').value,visible:$('product-visible').value==='true',images:productImagesDraft}; const i=data.products.findIndex(p=>p.id===id); if(i>=0)data.products[i]=item; else data.products.unshift(item); data=S.saveData(data); clearProduct(); renderProducts(); toast('商品を保存しました'); }
function renderProducts(){ $('product-table').innerHTML=data.products.map(p=>`<tr><td>${S.escapeHTML(p.name)}</td><td>${S.yen(p.price)}</td><td>${S.escapeHTML(p.category)}</td><td>${p.visible?'表示':'非表示'}</td><td><button class="mini-btn" onclick="editProduct('${p.id}')">編集</button> <button class="mini-btn danger" onclick="deleteProduct('${p.id}')">削除</button></td></tr>`).join(''); }
function renderProductThumbs(){ $('product-thumbs').innerHTML=productImagesDraft.map((src,i)=>`<div class="thumb"><img src="${src}"><button onclick="productImagesDraft.splice(${i},1);renderProductThumbs()">×</button></div>`).join(''); }
async function productImageChange(e){ const imgs=await S.saveImageFiles(e.target.files); productImagesDraft.push(...imgs); renderProductThumbs(); e.target.value=''; }
function clearBanner(){ bannerImageDraft=''; ['banner-id','banner-title','banner-text','banner-url','banner-order'].forEach(id=>$(id).value=''); $('banner-visible').value='true'; renderBannerThumb(); }
function editBanner(id){ const b=data.banners.find(x=>x.id===id); if(!b)return; $('banner-id').value=b.id; $('banner-title').value=b.title; $('banner-text').value=b.text; $('banner-url').value=b.url; $('banner-order').value=b.order||1; $('banner-visible').value=String(b.visible); bannerImageDraft=b.image||''; renderBannerThumb(); }
function deleteBanner(id){ if(!confirm('バナーを削除しますか？'))return; data.banners=data.banners.filter(b=>b.id!==id); data=S.saveData(data); renderBanners(); }
function saveBanner(){ const id=$('banner-id').value||S.generateId('banner'); const item={id,title:$('banner-title').value||'バナー',text:$('banner-text').value,url:$('banner-url').value||'#',order:Number($('banner-order').value||1),visible:$('banner-visible').value==='true',image:bannerImageDraft}; const i=data.banners.findIndex(b=>b.id===id); if(i>=0)data.banners[i]=item; else data.banners.unshift(item); data=S.saveData(data); clearBanner(); renderBanners(); toast('バナーを保存しました'); }
function renderBanners(){ $('banner-table').innerHTML=data.banners.sort((a,b)=>(a.order||0)-(b.order||0)).map(b=>`<div class="card banner-card"><div class="banner-img">${b.image?`<img src="${b.image}">`:'画像なし'}</div><div><h3>${S.escapeHTML(b.title)}</h3><p>${S.escapeHTML(b.text)}</p><p class="muted">${S.escapeHTML(b.url)} / ${b.visible?'表示':'非表示'} / 並び順${b.order}</p></div><div><button class="mini-btn" onclick="editBanner('${b.id}')">編集</button> <button class="mini-btn danger" onclick="deleteBanner('${b.id}')">削除</button></div></div>`).join(''); }
function renderBannerThumb(){ $('banner-thumb').innerHTML=bannerImageDraft?`<div class="thumb"><img src="${bannerImageDraft}"><button onclick="bannerImageDraft='';renderBannerThumb()">×</button></div>`:''; }
async function bannerImageChange(e){ const imgs=await S.saveImageFiles(e.target.files); bannerImageDraft=imgs[0]||bannerImageDraft; renderBannerThumb(); e.target.value=''; }
function renderOrders(){ $('order-list').innerHTML=data.orders.map(o=>`<div class="card"><h3>${S.escapeHTML(o.orderNumber)} <span class="pill">${S.escapeHTML(o.status)}</span></h3><p class="muted">${new Date(o.createdAt).toLocaleString('ja-JP')}</p><div class="two"><p><strong>お客様</strong><br>${S.escapeHTML(o.customer.name)} / ${S.escapeHTML(o.customer.kana)}<br>${S.escapeHTML(o.customer.tel)}<br>${S.escapeHTML(o.customer.email)}</p><p><strong>配送先</strong><br>〒${S.escapeHTML(o.shipping.zip)}<br>${S.escapeHTML(o.shipping.address)}<br>希望：${S.escapeHTML(o.shipping.delivery)}</p></div><div>${o.items.map(i=>`<div class="order-line"><span>${S.escapeHTML(i.name)} × ${i.qty}</span><strong>${S.yen(i.price*i.qty)}</strong></div>`).join('')}</div><p class="total-box">合計 ${S.yen(o.total)}</p><div class="two"><div><label>注文ステータス</label><select onchange="updateOrder('${o.id}','status',this.value)">${S.ORDER_STATUSES.map(st=>`<option ${o.status===st?'selected':''}>${st}</option>`).join('')}</select></div><div><label>発送状況</label><select onchange="updateOrder('${o.id}','shippingStatus',this.value)">${S.ORDER_STATUSES.map(st=>`<option ${o.shippingStatus===st?'selected':''}>${st}</option>`).join('')}</select></div></div><label>備考</label><textarea onchange="updateOrder('${o.id}','note',this.value)">${S.escapeHTML(o.note||'')}</textarea></div>`).join('')||'<p class="muted">注文はまだありません</p>'; }
function updateOrder(id,key,val){ const o=data.orders.find(x=>x.id===id); if(o){ o[key]=val; data=S.saveData(data); renderDashboard(); } }
function fillSettings(){ const s=data.settings; $('admin-email').value=s.adminEmail; $('admin-password').value=s.adminPassword; $('bank-name').value=s.bankInfo.bankName; $('branch-name').value=s.bankInfo.branchName; $('account-type').value=s.bankInfo.accountType; $('account-number').value=s.bankInfo.accountNumber; $('account-name').value=s.bankInfo.accountName; }
function saveSettings(){ data.settings.adminEmail=$('admin-email').value; data.settings.adminPassword=$('admin-password').value||'kubochan2025'; data.settings.bankInfo={bankName:$('bank-name').value,branchName:$('branch-name').value,accountType:$('account-type').value,accountNumber:$('account-number').value,accountName:$('account-name').value}; data=S.saveData(data); toast('設定を保存しました'); }
function thumbHTML(src,remove){ return src?`<div class="thumb"><img src="${src}">${remove?`<button onclick="${remove}">×</button>`:''}</div>`:''; }
function renderImageThumbs(){ $('hero-position').value=data.site.heroPosition||'center'; $('hero-thumb').innerHTML=thumbHTML(data.site.images.hero,"data.site.images.hero='';data=S.saveData(data);renderImageThumbs()"); $('main-thumb').innerHTML=thumbHTML(data.site.images.main,"data.site.images.main='';data=S.saveData(data);renderImageThumbs()"); $('story-thumbs').innerHTML=(data.site.images.stories||[]).map((src,i)=>thumbHTML(src,`data.site.images.stories.splice(${i},1);data=S.saveData(data);renderImageThumbs()`)).join(''); }
async function saveImages(){ data.site.heroPosition=$('hero-position').value; const hero=await S.saveImageFiles($('hero-image-file').files); if(hero[0]) data.site.images.hero=hero[0]; const main=await S.saveImageFiles($('main-image-file').files); if(main[0]) data.site.images.main=main[0]; const stories=await S.saveImageFiles($('story-images-file').files); data.site.images.stories=[...(data.site.images.stories||[]),...stories]; data=S.saveData(data); renderImageThumbs(); toast('画像を保存しました'); }
function refreshPreview(){ $('preview-frame').src='index.html?preview='+Date.now(); }
document.addEventListener('DOMContentLoaded',()=>{initLogin();initNav();setupEditor('story-editor-tools','story-body');setupEditor('product-editor-tools','product-body');setupEditor('shop-editor-tools','shop-body');$('save-site').onclick=saveSite;$('save-product').onclick=saveProduct;$('new-product').onclick=clearProduct;$('product-images').onchange=productImageChange;$('save-banner').onclick=saveBanner;$('new-banner').onclick=clearBanner;$('banner-image').onchange=bannerImageChange;$('save-settings').onclick=saveSettings;$('reset-data').onclick=()=>{if(confirm('初期化しますか？')){S.resetData();location.reload();}};$('save-images').onclick=saveImages;$('refresh-preview').onclick=refreshPreview;});
window.editProduct=editProduct; window.deleteProduct=deleteProduct; window.productImagesDraft=productImagesDraft; window.renderProductThumbs=renderProductThumbs; window.editBanner=editBanner; window.deleteBanner=deleteBanner; window.updateOrder=updateOrder; window.data=data; window.S=S; window.renderImageThumbs=renderImageThumbs;


/* --- 2026追加：ホーム上部に注文通知・サイト写真、Supabase設定、写真ギャラリー改善 --- */
renderDashboard=function(){const hero=data.site.images.hero;const notices=data.notifications.slice(0,20).map(n=>`<div class="notice"><strong>${S.escapeHTML(n.title)}</strong><br>${S.escapeHTML(n.message)}<br><span class="muted">${new Date(n.createdAt).toLocaleString('ja-JP')} / 通知先：${S.escapeHTML(n.to)}</span></div>`).join('')||'<p class="muted">通知はありません</p>';$('page-dashboard').innerHTML=`<h1>管理ホーム</h1><div class="card wood-card"><h2>注文通知</h2>${notices}</div><div class="dashboard-photo">${hero?`<img src="${hero}" alt="サイト写真">`:'ホーム画面トップ写真は「サイト編集」→「画像管理」から登録できます'}</div><div class="grid"><div class="card"><h3>商品数</h3><p class="price">${data.products.length}</p></div><div class="card"><h3>注文数</h3><p class="price">${data.orders.length}</p></div><div class="card"><h3>通知</h3><p class="price">${data.notifications.length}</p></div></div><div class="toolbar"><button class="btn" onclick="document.querySelector('[data-page=images]').click()">サイト写真を編集</button><button class="btn sub" onclick="document.querySelector('[data-page=orders]').click()">注文管理を見る</button></div>`;};
renderProductThumbs=function(){$('product-thumbs').innerHTML=productImagesDraft.map((src,i)=>`<div class="photo-thumb"><img src="${src}"><span>${i+1}枚目</span><button onclick="productImagesDraft.splice(${i},1);renderProductThumbs()">×</button></div>`).join('');};
renderProducts=function(){$('product-table').innerHTML=data.products.map(p=>`<tr><td><strong>${S.escapeHTML(p.name)}</strong><div class="photo-gallery">${(p.images||[]).slice(0,4).map((src,i)=>`<div class="photo-thumb"><img src="${src}"><span>${i+1}</span></div>`).join('')}</div><span class="muted">写真 ${p.images?.length||0}枚</span></td><td>${S.yen(p.price)}</td><td>${S.escapeHTML(p.category)}</td><td>${p.visible?'表示':'非表示'}</td><td><button class="mini-btn" onclick="editProduct('${p.id}')">編集</button> <button class="mini-btn danger" onclick="deleteProduct('${p.id}')">削除</button></td></tr>`).join('');};
renderOrders=function(){$('order-list').innerHTML=data.orders.map(o=>`<div class="card"><h3>${S.escapeHTML(o.orderNumber)} <span class="pill">${S.escapeHTML(o.status)}</span></h3><p class="muted">${new Date(o.createdAt).toLocaleString('ja-JP')}</p><div class="two"><p><strong>お客様</strong><br>${S.escapeHTML(o.customer.name)} / ${S.escapeHTML(o.customer.kana)}<br>${S.escapeHTML(o.customer.tel)}<br>${S.escapeHTML(o.customer.email)}</p><p><strong>配送先</strong><br>〒${S.escapeHTML(o.shipping.zip)}<br>${S.escapeHTML(o.shipping.address)}</p></div><div>${o.items.map(i=>`<div class="order-line"><span>${S.escapeHTML(i.name)} × ${i.qty}</span><strong>${S.yen(i.price*i.qty)}</strong></div>`).join('')}</div><p class="total-box">合計 ${S.yen(o.total)}</p><div class="two"><div><label>注文ステータス</label><select onchange="updateOrder('${o.id}','status',this.value)">${S.ORDER_STATUSES.map(st=>`<option ${o.status===st?'selected':''}>${st}</option>`).join('')}</select></div><div><label>発送状況</label><select onchange="updateOrder('${o.id}','shippingStatus',this.value)">${S.ORDER_STATUSES.map(st=>`<option ${o.shippingStatus===st?'selected':''}>${st}</option>`).join('')}</select></div></div><label>備考</label><textarea onchange="updateOrder('${o.id}','note',this.value)">${S.escapeHTML(o.note||'')}</textarea></div>`).join('')||'<p class="muted">ローカル注文はありません。Supabase保存を有効にした注文はSupabase側で確認してください。</p>';};
fillSettings=function(){const s=data.settings;s.supabase=Object.assign({enabled:false,url:'',anonKey:'',ordersTable:'orders'},s.supabase||{});$('page-settings').innerHTML=`<h1>設定</h1><div class="form-card"><label>管理者メールアドレス</label><input id="admin-email" type="email" value="${S.escapeHTML(s.adminEmail||'')}"><label>管理パスワード</label><input id="admin-password" value="${S.escapeHTML(s.adminPassword||'kubochan2025')}"><h2>Supabase注文保存設定</h2><label><input id="supabase-enabled" type="checkbox" class="check" ${s.supabase.enabled?'checked':''}> Supabaseへ注文を保存する</label><label>Supabase Project URL</label><input id="supabase-url" value="${S.escapeHTML(s.supabase.url||'')}" placeholder="https://xxxx.supabase.co"><label>Supabase anon key</label><input id="supabase-anon-key" value="${S.escapeHTML(s.supabase.anonKey||'')}" placeholder="sb_publishable_..."><label>注文テーブル名</label><input id="supabase-orders-table" value="${S.escapeHTML(s.supabase.ordersTable||'orders')}"><p class="privacy-note">注文テーブルは公開読み取り禁止・insertのみ許可にしてください。</p><h2>銀行振込先</h2><div class="two"><div><label>銀行名</label><input id="bank-name" value="${S.escapeHTML(s.bankInfo.bankName)}"></div><div><label>支店名</label><input id="branch-name" value="${S.escapeHTML(s.bankInfo.branchName)}"></div></div><div class="two"><div><label>種別</label><input id="account-type" value="${S.escapeHTML(s.bankInfo.accountType)}"></div><div><label>口座番号</label><input id="account-number" value="${S.escapeHTML(s.bankInfo.accountNumber)}"></div></div><label>口座名義</label><input id="account-name" value="${S.escapeHTML(s.bankInfo.accountName)}"><div class="toolbar"><button class="btn ok" id="save-settings">設定を保存</button><button class="btn danger" id="reset-data">ローカルデータ初期化</button></div></div>`;$('save-settings').onclick=saveSettings;$('reset-data').onclick=()=>{if(confirm('初期化しますか？')){S.resetData();location.reload();}};};
saveSettings=function(){data.settings.adminEmail=$('admin-email').value;data.settings.adminPassword=$('admin-password').value||'kubochan2025';data.settings.bankInfo={bankName:$('bank-name').value,branchName:$('branch-name').value,accountType:$('account-type').value,accountNumber:$('account-number').value,accountName:$('account-name').value};data.settings.supabase={enabled:$('supabase-enabled').checked,url:$('supabase-url').value.trim(),anonKey:$('supabase-anon-key').value.trim(),ordersTable:$('supabase-orders-table').value.trim()||'orders'};data=S.saveData(data);toast('設定を保存しました');};
