'use strict';
const S = window.KuboStorage; let data = S.loadData(); let cart = S.loadCart();
function visibleProducts(){return data.products.filter(p=>p.visible)}
function total(){return cart.reduce((a,i)=>a+i.price*i.qty,0)}
function syncProductMeta(){ cart = cart.map(i=>{ const p=data.products.find(p=>p.id===i.id); return p?{id:p.id,name:p.name,price:p.price,qty:i.qty}:i; }).filter(i=>i.qty>0); S.saveCart(cart); }
function render(){ syncProductMeta(); document.getElementById('product-picker').innerHTML=visibleProducts().map(p=>`<div class="cart-line"><div><strong>${S.escapeHTML(p.name)}</strong><br><span class="muted">${S.yen(p.price)} / ${S.escapeHTML(p.category)}</span></div><button class="mini-btn" onclick="add('${p.id}')">追加</button></div>`).join(''); document.getElementById('cart-list').innerHTML=cart.length?cart.map(i=>`<div class="cart-line"><div><strong>${S.escapeHTML(i.name)}</strong><br><span class="muted">${S.yen(i.price)} × ${i.qty}</span></div><div class="qty"><button onclick="qty('${i.id}',-1)">−</button><strong>${i.qty}</strong><button onclick="qty('${i.id}',1)">＋</button></div><strong>${S.yen(i.price*i.qty)}</strong></div>`).join(''):'<p class="muted">商品を追加してください。</p>'; document.getElementById('cart-total').textContent=S.yen(total()); }
function add(id){ const p=data.products.find(p=>p.id===id); if(!p)return; const f=cart.find(i=>i.id===id); if(f)f.qty++; else cart.push({id:p.id,name:p.name,price:p.price,qty:1}); S.saveCart(cart); render(); }
function qty(id,d){ const i=cart.find(x=>x.id===id); if(!i)return; i.qty+=d; cart=cart.filter(x=>x.qty>0); S.saveCart(cart); render(); }
function getForm(){ return {name:v('name'),kana:v('kana'),tel:v('tel'),email:v('email'),zip:v('zip'),address:v('address'),delivery:v('delivery'),note:v('note')}; }
function v(id){ return document.getElementById(id).value.trim(); }
function validate(){ const f=getForm(); const need=['name','kana','tel','email','zip','address']; for(const k of need){ if(!f[k]){ alert('必須項目を入力してください'); return false; } } if(!cart.length){ alert('商品を追加してください'); return false; } return true; }
function setStep(n){ [1,2,3].forEach(i=>document.getElementById('step'+i).classList.toggle('active',i===n)); }
function showConfirm(){ if(!validate())return; const f=getForm(); document.getElementById('input-panel').classList.add('hidden'); document.querySelector('.two').classList.add('hidden'); document.getElementById('confirm-panel').classList.remove('hidden'); setStep(2); document.getElementById('confirm-body').innerHTML=`<h3>お客様情報</h3><p>${S.escapeHTML(f.name)}（${S.escapeHTML(f.kana)}）<br>${S.escapeHTML(f.tel)} / ${S.escapeHTML(f.email)}<br>〒${S.escapeHTML(f.zip)} ${S.escapeHTML(f.address)}<br>配送希望：${S.escapeHTML(f.delivery)}</p><h3>注文商品</h3>${cart.map(i=>`<div class="order-line"><span>${S.escapeHTML(i.name)} × ${i.qty}</span><strong>${S.yen(i.price*i.qty)}</strong></div>`).join('')}<div class="total-box">合計 ${S.yen(total())}</div><p>決済方法：銀行振込</p><p>備考：${S.escapeHTML(f.note||'なし')}</p>`; }
function backInput(){ document.getElementById('confirm-panel').classList.add('hidden'); document.querySelector('.two').classList.remove('hidden'); document.getElementById('input-panel').classList.remove('hidden'); setStep(1); }
function submitOrder(){ const f=getForm(); const order={id:S.generateId('order'),orderNumber:'KP'+new Date().toISOString().slice(0,10).replaceAll('-','')+'-'+Math.random().toString(36).slice(2,6).toUpperCase(),createdAt:new Date().toISOString(),customer:{name:f.name,kana:f.kana,tel:f.tel,email:f.email},shipping:{zip:f.zip,address:f.address,delivery:f.delivery},items:cart,total:total(),paymentMethod:'銀行振込',paymentStatus:'銀行振込待ち',shippingStatus:'受付済み',status:'銀行振込待ち',note:f.note}; data=S.loadData(); data.orders.unshift(order); S.saveData(data); S.sendOrderNotification(order); S.clearCart(); cart=[]; complete(order); }
function complete(order){ setStep(3); document.getElementById('confirm-panel').classList.add('hidden'); document.getElementById('complete-panel').classList.remove('hidden'); const b=S.loadData().settings.bankInfo; document.getElementById('complete-body').innerHTML=`<p><strong>注文番号：</strong>${S.escapeHTML(order.orderNumber)}</p><p><strong>お支払い金額：</strong>${S.yen(order.total)}</p><hr><p><strong>銀行名：</strong>${S.escapeHTML(b.bankName)}<br><strong>支店名：</strong>${S.escapeHTML(b.branchName)}<br><strong>種別：</strong>${S.escapeHTML(b.accountType)}<br><strong>口座番号：</strong>${S.escapeHTML(b.accountNumber)}<br><strong>名義：</strong>${S.escapeHTML(b.accountName)}</p><p class="muted">お振込み確認後、発送準備に入ります。</p>`; }
document.addEventListener('DOMContentLoaded',()=>{render(); document.getElementById('to-confirm').onclick=showConfirm; document.getElementById('back-input').onclick=backInput; document.getElementById('submit-order').onclick=submitOrder;}); window.add=add; window.qty=qty;
